version: '3'
services:
  luca-blockchain-svc:
    hostname: luca-blockchain-svc-0
    image: blengineering.azurecr.io/blengineering/luca-blockchain-svc:er-dev
    ports:
      - '8085:9899'
    environment:
      - SERVER_PORT=9899
      - WEB3_HTTP=http://toorak01.ledgerium.io:8545
      - PROOF_CONTRACT_ADDRESS=0xEFA87544B7a6975c715f94905697B854ed28B9A8
      - PUBLIC_KEY=0x2296365c074db8beCE7D8443D1ECE22384aE1Ee7
      - PRIVATE_KEY=0x59611453a73dbe358e416b4273a2621f0b2ceb91edfd6fe7143620f80e183a4e
      - MONGO_URL=mongodb+srv://luca-dev:PNob12ZWGTQlEVBN@cluster0-gtefe.mongodb.net/contractstore?retryWrites=true&w=majority
    restart: always
    networks:
      luca_dev_net:
        ipv4_address: 172.16.249.13
networks:
  luca_dev_net:
    external: true